# Generated by Django 3.2.6 on 2021-08-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niveles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivel',
            options={'verbose_name_plural': 'Niveles'},
        ),
    ]
