# Generated by Django 3.2.6 on 2021-08-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ptos_totales',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
