# Generated by Django 3.2.6 on 2021-09-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_ptos_totales'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nivel',
            field=models.CharField(blank=True, default='Facil', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ptos_totales',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
