# Generated by Django 3.2.6 on 2021-09-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20210901_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ptos_totales',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
