# Generated by Django 3.2.6 on 2021-08-30 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuestionariomodel',
            old_name='preguntas',
            new_name='pregunta',
        ),
    ]
