# Generated by Django 3.2.6 on 2021-09-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0002_rename_preguntas_cuestionariomodel_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionariomodel',
            name='correct',
            field=models.CharField(choices=[('rta1', 'Respuesta 1'), ('rta2', 'Respuesta 2'), ('rta3', 'Respuesta 3')], default=' ', max_length=4),
        ),
    ]
